#!/usr/bin/env bash

# Check if the number of arguments is less than 4
if [ $# -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Transfer the file to the server using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
