#!/usr/bin/env bash
# Displays "alx  School" 10 times using a while loop.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Holberton School"
  (( count++ ))
done
